# OBJS specifies which files to compile as part of the project
OBJ_SOURCE = pruferSequence.cpp

# OBJ_NAME specifies the name of our exectuable
OBJ_NAME = Prufer

# This is the target that compiles our executable
all : $(OBJ_SOURCE)
	g++ $(OBJ_SOURCE) -w -o $(OBJ_NAME)
